name: Check internationalization files

on:
  push:
    branches:
      - master
    paths:
      - 'internationalization/*'

jobs:
  check:
    name: Report gaps
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Load Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Run Ruby script
      working-directory: ./.github/actions 
      run: ruby int_check.rb
    - name: Commit and push files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Automated test push"
        git push -u origin master 
