name: Check internationalization files

on:
  push:
    branches:
      - master
    paths:
      - 'internationalization/*'

jobs:
  int_check:
    name: Report gaps
    runs-on: ubuntu-latest
    steps:
      - name: Check
      uses: actions/setup-ruby@v1
      run: ruby actions/int_check.rb
