name: Check internationalization files

on:
  push:
    branches:
      - master
    paths:
      - 'internationalization/*'

jobs:
  my_job:
    name: report gaps
    runs-on: ubuntu-latest
    uses: actions/setup-ruby@v1
    run: ruby actions/int_check.rb
